# Nom du workflow
name: Docker CI/CD

# Définit quand le workflow sera déclenché
on:
  push:
    branches: [ "main" ]  # Déclenché lors d'un push sur la branche main
  pull_request:
    branches: [ "main" ]  # Déclenché lors d'une pull request vers main

env:
  REG_NAME: "vandenbroeck-nolhan-registrery" # Nom du registy
  IMAGE_NAME: "worldcupCICD-DockerHub-app" # Nom de votre image

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: login
        run: | # le echo, | et stdin c'est pour ne pas afficher le mdp dans les logs 
          echo "${{ secrets.PASSWORD }}" | docker login ${{ env.REG_NAME }} -u ${{ secrets.USERNAME }} --password-stdin
      - name: build
        run: |
          docker build -t ${{ env.REG_NAME }}/${{ env.IMAGE_NAME }}:latest ./src
      - name:
        run: | 
          docker push ${{ env.REG_NAME }}/${{ env.IMAGE_NAME }}:latest